services:
  postgres:
    image: postgres:latest
    container_name: url_shortener_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network

volumes:
  postgres_data:

networks:
  url-shortener-network:
    driver: bridge